# Default values for xavier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: gateway
env: staging
maxReplicas: 10
cpuUsage: 80

image:
  registry: nindooai.azurecr.io
  name: monaco-gateway
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  portName: http

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  hostname: monaco.nindoo.io

environment: {}

resources:
  requests:
    cpu: 250m
