# Default values for xavier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: api-gateway
env: staging
maxReplicas: 10
cpuUsage: 80

image:
  registry: chegaai.azurecr.io
  name: api-gateway
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  portName: http

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  hostname: api.chega.ai

environment: {}

resources:
  requests:
    cpu: 250m
    memory: 128M
  limits:
    cpu: 500m
    memory: 256M
