apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    version: {{.Values.image.tag}}
    env: {{ .Values.env }}
  {{- with .Values.ingress.annotations }}
  annotations:
    kubernetes.io/tls-acme: 'true'
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.name }}
              servicePort: {{ .Values.service.portName }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.name }}-tls-cert
