apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    version: {{ .Values.image.tag }}
    env: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: {{ .Values.image.tag }}
        env: {{ .Values.env }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MAPS_FILE_URL
              value: {{ required "You must set environment.MAPS_FILE_URL" .Values.environment.MAPS_FILE_URL | quote }}
            - name: AUTH_JWT_AUDIENCE
              value: {{ default "api-gateway" .Values.environment.AUTH_JWT_AUDIENCE | quote }}
            - name: AUTH_JWT_ISSUER
              value: {{ default "urn:chega.ai:issuer" .Values.environment.AUTH_JWT_ISSUER | quote }}
            - name: NODE_ENV
              value: {{.Release.Namespace}}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: docker-registry-credentials
